# Generated by Django 4.2.2 on 2023-06-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_seravis_team_portfolio_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seravis',
            new_name='Services',
        ),
    ]
