# Generated by Django 4.2.2 on 2023-06-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_rename_seravis_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malumot_saqlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=60)),
                ('message', models.TextField()),
            ],
        ),
    ]
