# Generated by Django 4.2.2 on 2023-06-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0005_malumot_saqlash_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
